import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], display:'swap', variable:'--font-in' })
const roboto = Roboto({ subsets: ['latin'], display:'swap', variable:'--font-r', weight:["100", "300", "400", "500", "700", "900"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable} font-r bg-blue-500`}>{children}</body>
    </html>
  )
}
